# Generated by Django 5.2.8 on 2025-12-10 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('itineraries_per_month', models.CharField(default='1', max_length=20)),
                ('videos_per_month', models.IntegerField(default=0)),
                ('video_price', models.DecimalField(decimal_places=2, default=5.99, max_digits=10)),
                ('video_quality', models.CharField(default='standard', max_length=20)),
                ('chatbot_access', models.BooleanField(default=True)),
                ('customization', models.BooleanField(default=True)),
                ('social_sharing', models.BooleanField(default=True)),
                ('exclusive_deals', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['price'],
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.plan'),
        ),
    ]
