# Generated by Django 5.2.9 on 2026-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_chatmessage_celery_task_id_chatmessage_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogeneration',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='fastapi_itinerary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videogeneration',
            name='fastapi_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
