# Generated by Django 6.0 on 2026-01-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_videogeneration_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogeneration',
            name='custom_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videogeneration',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ai_services.itinerary'),
        ),
    ]
