# Generated by Django 6.0 on 2026-01-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_videogeneration_custom_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogeneration',
            name='custom_destination',
        ),
        migrations.AlterField(
            model_name='videogeneration',
            name='itinerary',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ai_services.itinerary'),
            preserve_default=False,
        ),
    ]
